### ISSUE TITLE
The demo on share.streamlit.io

### ISSUE THREAD

**Issue by chiehpower** [okld/streamlit-elements#1]
Hi @okld,

Thanks for your contribution to sharing this awesome Streamlit component! 

I am wondering would you like to share the codes of the demo on [share.streamlit.io](https://share.streamlit.io/okld/streamlit-gallery/main?p=elements)?

I wanna try the function of switching the light-dark theme for each element and the feature of checking out different items in one element.

![2022-05-0348](https://user-images.githubusercontent.com/32332200/166409585-d5666d28-c95c-4c06-be8a-26be97b3c499.png)

Thank you in advance!

Best regards,
Chieh

**Comment by okld** [comment]
Hello @chiehpower,

The code is available in this repository: https://github.com/okld/streamlit-gallery
Also, in general you can get the source code of share.streamlit.io apps in the menu in the top right corner, as long as the github repository is public.

![image](https://user-images.githubusercontent.com/65978885/166492955-02c98a05-c790-4176-81f4-cd4607643abe.png)

Regarding the dark/light theme switch, the button is defined [here](https://github.com/okld/streamlit-gallery/blob/e5e4ae9f2693851ab66964a35da02dd20fd27a2b/streamlit_gallery/components/elements/dashboard/dashboard.py#L47-L51), with a callback that changes the attribute `_dark_mode` of my `Item` class. And I choose the correct editor theme accordingly [here](https://github.com/okld/streamlit-gallery/blob/e5e4ae9f2693851ab66964a35da02dd20fd27a2b/streamlit_gallery/components/elements/dashboard/editor.py#L55).

**Comment by chiehpower** [comment]
Hi @okld,

Got it!!

Thanks for your pointing out!
I really appreciate your contributions!

Best regards,
Chieh
