### ISSUE TITLE
Usage of mui.Tooltip throws ElementsFrontendError

### ISSUE THREAD

**Issue by Toxiiin** [okld/streamlit-elements#6]
Hi everyone, hi @okld,

I was trying to use some tooltips with the mui.Tooltip element, but if I do, it throws an ElementsFrontendError:

`ElementsFrontendError: In elements frame 'streamlit_elements.core.frame.elements_frame.tooltip_test': Cannot read properties of undefined (reading 'addEventListener')`

I have used the following snippet:

```
with elements("tooltip_test"):
    with mui.Tooltip(title="Tooltip"):
        mui.Typography(
            "Tooltip"
        )
```

Is there something I missed?

## Expected Behavior
Tooltip shows up as expected.

## Current Behavior
Usage of mui.Tooltip results in an ElementsFrontendError.

`ElementsFrontendError: In elements frame 'streamlit_elements.core.frame.elements_frame.tooltip_test': Cannot read properties of undefined (reading 'addEventListener')`

## Steps to Reproduce
1. Use the mui.Tooltip element in your script like:
    ```
    with elements("tooltip_test"):
        with mui.Tooltip(title="Tooltip"):
            mui.Typography(
                "Tooltip"
            )
    ```

## Context (Environment)
- Python 3.8.13
- streamlit==1.9.2
- streamlit-elements==0.1.0

**Comment by Sanuki-073** [comment]
Hello @Toxiiin,

I found the answer of this issue.

```
from streamlit_elements import html
# import others
....

with elements("tooltip_test"):
    with mui.Tooltip(title="Tooltip"):
        with html.span:
            mui.Typography(
                 "Tooltip"
            )
```

**Comment by Toxiiin** [comment]
Hi @Sanuki-073,

never thought would get an answer after this time. 😃
Thank you for sharing the answer! 👍
